---
title: "codebook.Rmd"
author: "Marc Bauchet"
date: "15 May 2021"
output: html_document
editor_options: 
  markdown: 
    wrap: 72
---

This code book explains the data, variables and functions used in
*run_analysis.R* script for Coursera's Data Cleaning course's week4
project. The functions described below are combined in the script into a
pipeline that calculates the average of each variable for each activity
and each subject.\

## **Script Name:** *run_analysis.R*

### Data Sets

Project data can be manually downloaded & unzipped [from
here.](https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip){.uri}

Based on the unzipped data file, the files used by ***run_analysis.R***
are:

| A ssociated R variable name | File in "UCI HAR Dataset" folder | Content                                      |
|-----------------------------|----------------------------------|----------------------------------------------|
| train_tbl                   | trai n/**X_train.txt**           | training set, 300+ obs. per each 21 subjects |
| test_tbl                    | te st/**X_test.txt**             | test set, 300+ obs. per each 9 subjects      |
| (fea turefile)              | **features.txt**                 | array of 561 names for each variable         |
| (t rainfile)                | trai n/**y_train.txt**           | activity IDs of the training set (all rows)  |
| ( testfile)                 | te st/**y_test.txt**             | activity IDs of the test set (all rows)      |
| subj ect_train              | train/**su bject_train.txt**     | subject IDs of the training set (all rows)   |
| sub ject_test               | test/**s ubject_test.txt**       | subject IDs of the test set (all rows)       |
| out_file                    | **TrainTes t.MeanStdev.txt**     | tidy dataset produced by the script          |

[Click here for the full description of the
data.](http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones){.uri}

### Main Variables

**`final_tbl`** (a tibble: 180 x 68): final tidy data set as per task
\#5, with the average of each variable for each activity and each
subject.

**`activity_IDs`**

**`activity_names`**

**`meanstd_colnames_desc`**

**`subject_IDs`**

### Functions

#### `merge_traintest( trainfile, testfile )`

trainfile:

textfile:

#### `relabel_variables( mytbl )`

mytbl:

#### `set_activities( mytbl, trainfile, testfile )`

mytbl:

trainfile:

textfile:

#### `relabel_variables( mytbl )`

mytbl

#### `add_subjects( mytbl, trainfile, testfile )`

mytbl:

trainfile:

testfile:
